# import packages/modules
import pycuc
from rich import print

# check version
print(pycuc.__version__)

# =====================================
# CHECK REFERENCES
# =====================================
# gibbs free energy
print(pycuc.check_reference('FLOW_RATE'))


# =====================================
# CONVERT FROM TO (short format)
# =====================================
# ! flow-rate
# NOTE: volume flow rate
res = pycuc.to(1, 'L/s => m3/s')
print(f"1 L/s = {res} m3/s")
# superior unicode support
res = pycuc.to(1, 'L/s => m³/s')
print(f"1 L/s = {res} m³/s")
res = pycuc.to(1, 'm3/s => L/s')
print(f"1 m3/s = {res} L/s")
res = pycuc.to(1, 'mL/s => m3/s')
print(f"1 mL/s = {res} m3/s")
res = pycuc.to(1, 'm3/s => mL/s')
print(f"1 m3/s = {res} mL/s")
res = pycuc.to(1, 'cm3/s => m3/s')
print(f"1 cm3/s = {res} m3/s")
res = pycuc.to(1, 'm3/s => cm3/s')
print(f"1 m3/s = {res} cm3/s")
res = pycuc.to(1, 'ft3/s => m3/s')
print(f"1 ft3/s = {res} m3/s")
res = pycuc.to(1, 'm3/s => ft3/s')
print(f"1 m3/s = {res} ft3/s")
# superior unicode support
res = pycuc.to(1, 'ft³/s => m3/s')
print(f"1 ft³/s = {res} m3/s")
res = pycuc.to(1, 'm3/s => ft³/s')
print(f"1 m3/s = {res} ft³/s")
res = pycuc.to(1, 'm³/min => m³/s')
print(f"1 m³/min = {res} m³/s")
res = pycuc.to(1, 'm3/min => m3/s')
print(f"1 m3/min = {res} m3/s")
res = pycuc.to(1, 'gal/s => m3/s')
print(f"1 gal/s = {res} m3/s")
res = pycuc.to(1, 'm3/s => gal/s')
print(f"1 m3/s = {res} gal/s")
res = pycuc.to(1, 'ft3/min => m3/s')
print(f"1 ft3/min = {res} m3/s")
res = pycuc.to(1, 'm3/s => ft3/min')
print(f"1 m3/s = {res} ft3/min")
res = pycuc.to(1, 'gal/min => m3/s')
print(f"1 gal/min = {res} m3/s")
res = pycuc.to(1, 'm3/s => gal/min')
print(f"1 m3/s = {res} gal/min")
res = pycuc.to(1, 'barrel/day => m3/s')
print(f"1 barrel/day = {res} m3/s")

# NOTE: mass flow rate
res = pycuc.to(1, 'kg/s => g/s')
print(f"1 kg/s = {res} g/s")
res = pycuc.to(1, 'g/s => kg/s')
print(f"1 g/s = {res} kg/s")
res = pycuc.to(1, 'tonne/s => kg/s')
print(f"1 tonne/s = {res} kg/s")
res = pycuc.to(1, 'kg/s => tonne/s')
print(f"1 kg/s = {res} tonne/s")
res = pycuc.to(1, 'lb/s => g/s')
print(f"1 lb/s = {res} g/s")
res = pycuc.to(1, 'g/s => lb/s')
print(f"1 g/s = {res} lb/s")
res = pycuc.to(1, 'lbm/s => g/s')
print(f"1 lbm/s = {res} g/s")
res = pycuc.to(1, 'g/s => lbm/s')
print(f"1 g/s = {res} lbm/s")
res = pycuc.to(1, 'slug/s => g/s')
print(f"1 slug/s = {res} g/s")
res = pycuc.to(1, 'g/s => slug/s')
print(f"1 g/s = {res} slug/s")
res = pycuc.to(1, 'lbm/min => g/s')
print(f"1 lbm/min = {res} g/s")
res = pycuc.to(1, 'g/s => lbm/min')
print(f"1 g/s = {res} lbm/min")
res = pycuc.to(1, 'slug/min => g/s')
print(f"1 slug/min = {res} g/s")
res = pycuc.to(1, 'g/s => slug/min')
print(f"1 g/s = {res} slug/min")
res = pycuc.to(1, 'lbm/hr => g/s')
print(f"1 lbm/hr = {res} g/s")
res = pycuc.to(1, 'g/s => lbm/hr')
print(f"1 g/s = {res} lbm/hr")
res = pycuc.to(1, 'slug/hr => g/s')
print(f"1 slug/hr = {res} g/s")
res = pycuc.to(1, 'g/s => slug/hr')
print(f"1 g/s = {res} slug/hr")
res = pycuc.to(1, 'tonne/day => kg/s')
print(f"1 tonne/day = {res} kg/s")
res = pycuc.to(1, 'kg/s => tonne/day')
print(f"1 kg/s = {res} tonne/day")
res = pycuc.to(1, 'lbm/day => g/s')
print(f"1 lbm/day = {res} g/s")
res = pycuc.to(1, 'g/s => lbm/day')
print(f"1 g/s = {res} lbm/day")
res = pycuc.to(1, 'slug/day => g/s')
print(f"1 slug/day = {res} g/s")
res = pycuc.to(1, 'g/s => slug/day')
print(f"1 g/s = {res} slug/day")
res = pycuc.to(1, 'tonne/hr => kg/s')
print(f"1 tonne/hr = {res} kg/s")
res = pycuc.to(1, 'kg/s => tonne/hr')
print(f"1 kg/s = {res} tonne/hr")


# NOTE: molar flow rate
res = pycuc.to(1, 'mol/s => mmol/s')
print(f"1 mol/s = {res} mmol/s")
res = pycuc.to(1, 'mmol/s => mol/s')
print(f"1 mmol/s = {res} mol/s")
res = pycuc.to(1, 'kmol/s => mol/s')
print(f"1 kmol/s = {res} mol/s")
res = pycuc.to(1, 'mol/s => kmol/s')
print(f"1 mol/s = {res} kmol/s")
res = pycuc.to(1, 'kmol/hr => mol/s')
print(f"1 kmol/hr = {res} mol/s")
res = pycuc.to(1, 'mol/s => kmol/hr')
print(f"1 mol/s = {res} kmol/hr")
res = pycuc.to(1, 'mol/min => mmol/s')
print(f"1 mol/min = {res} mmol/s")
res = pycuc.to(1, 'mmol/s => mol/min')
print(f"1 mmol/s = {res} mol/min")
res = pycuc.to(1, 'kmol/min => mol/s')
print(f"1 kmol/min = {res} mol/s")
res = pycuc.to(1, 'mol/s => kmol/min')
print(f"1 mol/s = {res} kmol/min")
res = pycuc.to(1, 'kmol/day => mol/s')
print(f"1 kmol/day = {res} mol/s")
res = pycuc.to(1, 'mol/s => kmol/day')
print(f"1 mol/s = {res} kmol/day")
